### ISSUE TITLE
No results returned  error is raised often when generating dataframes

### ISSUE THREAD

**Issue by epicvhbennetts** [Sinaptik-AI/pandas-ai#1053]
### System Info

Azure OpenAI
Pandas AI version 2.012
ChatGPT version 3.5 Turbo

### 🐛 Describe the bug

When submitting a prompt that asks the results to be shown as a table, I often get a no results returned error.
For example for the prompt:
**show me the number of employees hired by year as a table**

I get this log:

2024-03-19 16:14:27 [INFO] Code generated:
            ```
            import pandas as pd
```

# Filter the dataframe to include only the relevant columns
df_filtered = dfs[0][['Employee start date']]

# Extract the year from the 'Employee start date' column
df_filtered['Year'] = df_filtered['Employee start date'].dt.year

# Group the data by year and count the number of employees hired in each year
df_grouped = df_filtered.groupby('Year').size().reset_index(name='Number of Employees Hired')

# Sort the data by year in ascending order
df_sorted = df_grouped.sort_values('Year')

# Display the table
df_sorted
            ```

2024-03-19 16:14:27 [INFO]
Code running:
```
df_filtered = dfs[0][['Employee start date']]
df_filtered['Year'] = df_filtered['Employee start date'].dt.year
df_grouped = df_filtered.groupby('Year').size().reset_index(name='Number of Employees Hired')
df_sorted = df_grouped.sort_values('Year')
df_sorted
        ```
<string>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

2024-03-19 16:14:27 [ERROR] Failed with error: Traceback (most recent call last):
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 64, in execute
    result = code_manager.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\helpers\code_manager.py", line 211, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned

2024-03-19 16:14:27 [ERROR] Pipeline failed on step 5: No result returned
Traceback (most recent call last):
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 281, in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 93, in execute
    raise e
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 64, in execute
    result = code_manager.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDVHE\AppData\Local\anaconda3\envs\pandasAIV20\Lib\site-packages\pandasai\helpers\code_manager.py", line 211, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned







```

**Comment by ssling0817** [comment]
Any updates? 
@epicvhbennetts Do you find any solutions? I also have the same issue. Thank you!
