### ISSUE TITLE
duckdb.IOException: IO Error: Trying to read a database file with version number 64, but we can only read version 51.

### ISSUE THREAD

**Issue by xvgaoxing2023** [Sinaptik-AI/pandas-ai#1078]
### System Info

pandasai  2.0.26
Python 3.10

### 🐛 Describe the bug

agent = SmartDataframe(sales_by_country)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuzhenkun/anaconda3/envs/python3.10/lib/python3.10/site-packages/pandasai/smart_dataframe/__init__.py", line 62, in __init__
    self._agent = Agent([df], config=config)
  File "/home/xuzhenkun/anaconda3/envs/python3.10/lib/python3.10/site-packages/pandasai/agent/base.py", line 76, in __init__
    self.context = PipelineContext(
  File "/home/xuzhenkun/anaconda3/envs/python3.10/lib/python3.10/site-packages/pandasai/pipelines/pipeline_context.py", line 35, in __init__
    self.cache = cache if cache is not None else Cache()
  File "/home/xuzhenkun/anaconda3/envs/python3.10/lib/python3.10/site-packages/pandasai/helpers/cache.py", line 32, in __init__
    self.connection = duckdb.connect(self.filepath)
duckdb.IOException: IO Error: Trying to read a database file with version number 64, but we can only read version 51.
The database file was created with an newer version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

**Comment by ssling0817** [comment]
Do you solve the issue? I have the same one, thanks!
