### ISSUE TITLE
pandasai.exceptions.PandasAIApiCallError: Training failed because of internal server error try again later!

### ISSUE THREAD

**Issue by vpurandara** [Sinaptik-AI/pandas-ai#1081]
### System Info

Please share your system info with us.
OS version: ubuntu: 22.04
Python version: python 3.9
The current version of pandasai being used: 2.0.19

### 🐛 Describe the bug

Still 2 days before it is working fine, currently it is throwing error, even update to pandasa==2.0.26 but still same

```
2024-04-01 14:54:36 [INFO] Agent successfully trained on the data
2024-04-01 14:54:36 [INFO] Question: Use 'pd.Timestamp.now()' for relative points in time, e.g. 'this month'. 'this week', 'yesterday', 'last week'. How Many Leads This Week
2024-04-01 14:54:36 [INFO] Running PandasAI with openai LLM...
2024-04-01 14:54:36 [INFO] Prompt ID: e6cc1467-c3dd-40b0-9aec-4876a98add15
2024-04-01 14:54:36 [INFO] Executing Pipeline: GenerateChatPipeline
2024-04-01 14:54:36 [INFO] Executing Step 0: ValidatePipelineInput
2024-04-01 14:54:36 [INFO] Executing Step 1: CacheLookup
2024-04-01 14:54:36 [INFO] Executing Step 2: PromptGeneration
2024-04-01 14:54:37 [ERROR] Pipeline failed on step 2: Training failed because of internal server error try again later!
Traceback (most recent call last):
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 281, in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/pipelines/chat/prompt_generation.py", line 37, in execute
    self.logger.log(f"Using prompt: {prompt}")
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/prompts/base.py", line 54, in __str__
    return self.to_string()
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/prompts/base.py", line 49, in to_string
    self._resolved_prompt = self.prompt.render(**self.props)
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/prompts/templates/generate_python_code.tmpl", line 19, in top-level template code
    {% include 'shared/vectordb_docs.tmpl' with context %}
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/prompts/templates/shared/vectordb_docs.tmpl", line 1, in top-level template code
    {% if context.vectorstore %}{% set documents = context.vectorstore.get_relevant_qa_documents(context.memory.get_last_message()) %}
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/vectorstores/bamboo_vectorstore.py", line 56, in get_relevant_qa_documents
    docs = self._session.get(
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/helpers/request.py", line 34, in get
    return self.make_request("GET", path, **kwargs)["data"]
  File "/home/purandara/anaconda3/envs/propflo-ai2/lib/python3.9/site-packages/pandasai/helpers/request.py", line 71, in make_request
    raise PandasAIApiCallError(data["message"])
pandasai.exceptions.PandasAIApiCallError: Training failed because of internal server error try again later!
```
@gventuri

**Comment by fralu07** [comment]
i have the same problem. 

My setup:
MacOs 14.3.1
Jupyter lap 4.1.4 run in docker
Python version: 3.11
pandasai: 2.0.26

`Traceback (most recent call last):
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 283](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/chat/generate_chat_pipeline.py#line=282), in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py", line 137](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py#line=136), in run
    raise e
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py", line 101](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py#line=100), in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/chat/prompt_generation.py", line 37](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/pipelines/chat/prompt_generation.py#line=36), in execute
    self.logger.log(f"Using prompt: {prompt}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/prompts/base.py", line 54](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/prompts/base.py#line=53), in __str__
    return self.to_string()
           ^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/prompts/base.py", line 49](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/prompts/base.py#line=48), in to_string
    self._resolved_prompt = self.prompt.render(**self.props)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/jinja2/environment.py", line 1301](http://localhost:10000/opt/conda/lib/python3.11/site-packages/jinja2/environment.py#line=1300), in render
    self.environment.handle_exception()
  File "[/opt/conda/lib/python3.11/site-packages/jinja2/environment.py", line 936](http://localhost:10000/opt/conda/lib/python3.11/site-packages/jinja2/environment.py#line=935), in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/prompts/templates/generate_python_code.tmpl", line 19](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/prompts/templates/generate_python_code.tmpl#line=18), in top-level template code
    {% include 'shared[/vectordb_docs.tmpl](http://localhost:10000/vectordb_docs.tmpl)' with context %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/prompts/templates/shared/vectordb_docs.tmpl", line 1](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/prompts/templates/shared/vectordb_docs.tmpl#line=0), in top-level template code
    {% if context.vectorstore %}{% set documents = context.vectorstore.get_relevant_qa_documents(context.memory.get_last_message()) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/vectorstores/bamboo_vectorstore.py", line 56](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/vectorstores/bamboo_vectorstore.py#line=55), in get_relevant_qa_documents
    docs = self._session.get(
           ^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/helpers/request.py", line 34](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/helpers/request.py#line=33), in get
    return self.make_request("GET", path, **kwargs)["data"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/pandasai/helpers/request.py", line 71](http://localhost:10000/opt/conda/lib/python3.11/site-packages/pandasai/helpers/request.py#line=70), in make_request
    raise PandasAIApiCallError(data["message"])
pandasai.exceptions.PandasAIApiCallError: Training failed because of internal server error try again later!`

**Comment by HITjunle** [comment]
I still do not solve the problem, but you can ignore pandasai api by using the code:
```python
    os.environ.pop("PANDASAI_API_KEY", None)
    llm = OpenAI()
    df = pd.read_csv(path)
    agent = Agent(df, config={"llm": llm, "enable_cache": False}, description=description)
``` 
and it will work by ignoring pandasai's training data.

**Comment by vpurandara** [comment]
@HITjunle , this resolves the issue temporarily. Thanks for resposne.
