### ISSUE TITLE
NameError: name 'pl' is not defined

### ISSUE THREAD

**Issue by aby1234567** [Sinaptik-AI/pandas-ai#1162]
### System Info

OS version - Windows 11
pandasai version - 2.0.42
python version - 3.11.5

### 🐛 Describe the bug

Im trying to use Agent or smartdataframe with polars and this is the issue that i'm getting.

2024-05-17 09:27:55.420 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\aby\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 60
                                                                                                         00, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\aby\Untitled Folder\Streamlit Project\Analyze_with_AI.py", line 77, in <module>
    sdf = SmartDataframe(df, config={"llm": llm})
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aby\anaconda3\Lib\site-packages\pandasai\smart_dataframe\__init__.py", line 62, in __init__
    self._agent = Agent([df], config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aby\anaconda3\Lib\site-packages\pandasai\agent\base.py", line 72, in __init__
    dfs = self.get_dfs(dfs)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\aby\anaconda3\Lib\site-packages\pandasai\agent\base.py", line 211, in get_dfs
    connectors.append(PolarsConnector({"original_df": df}))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aby\anaconda3\Lib\site-packages\pandasai\connectors\polars.py", line 66, in __init__     
    self._load_df(self.config.original_df)
  File "C:\Users\aby\anaconda3\Lib\site-packages\pandasai\connectors\polars.py", line 76, in _load_df     
    if isinstance(df, pl.Series):
                      ^^
NameError: name 'pl' is not defined

**Comment by gventuri** [comment]
@aby1234567 do you have polars installed?

**Comment by aby1234567** [comment]
@gventuri yes, i do
