### ISSUE TITLE
Issue: pandasAI Authentication Error with OpenAI

### ISSUE THREAD

**Issue by Tashu014** [Sinaptik-AI/pandas-ai#1187]
### Discussed in https://github.com/Sinaptik-AI/pandas-ai/discussions/1171

<div type='discussions-op-text'>

<sup>Originally posted by **Tashu014** May 21, 2024</sup>
## Code Snippet:
from pandasai import SmartDataframe
from pandasai.connectors import MySQLConnector
from pandasai.llm import OpenAI

llm = OpenAI(api_token="your_api_key_here")

mysql_connector = MySQLConnector(
    config={
        "host":"localhost",
        "port":3306,
        "database":"superstore",
        "username":"root",
        "password":"root",
        "table":"superstore",
        "where":[
            ["CustomerName", "=", "Claire Gute"],
        ],
    }
)

df = SmartDataframe(mysql_connector, config={"llm": llm})

print(df.chat('What is the address?'))

## Error:
Traceback (most recent call last):
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 307, in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\pipelines\chat\code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\llm\base.py", line 201, in generate_code
    response = self.call(instruction, context)
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\llm\base.py", line 391, in call
    self.chat_completion(self.last_prompt, memory)
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\pandasai\llm\base.py", line 365, in chat_completion
    response = self.client.create(**params)
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\openai\resources\chat\completions.py", line 590, in create
    return self._post(
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
  File "D:\Desktop\Relinns\pandasai\venv\lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-w1LNb***************************************Sf96. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Unfortunately, I was not able to answer your question, because of the following error:

Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-w1LNb***************************************Sf96. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

## Description:
I've ensured my OpenAI API key is correct (replaced with "your_api_key_here" in the code), but I'm still getting this authentication error.

## Question:
Has anyone else faced a similar issue with pandasAI and OpenAI authentication? Any suggestions on how to resolve this would be greatly appreciated.

## Additional information:
pandasai                  2.0.43
openai                     1.30.1</div>

**Comment by gventuri** [comment]
@Tashu014 that message is taken directly from the OpenAI sdk, so I don't think it's an issue strictly related to PandasAI. I've just tested and it works great for me with my OpenAI key. Please, make sure the API key is valid and that there are no outages with the OpenAI server!
