### ISSUE TITLE
Unable to save chart image, or setting not to save chart will throw error "No such file or directory"

### ISSUE THREAD

**Issue by wuhuanyan** [Sinaptik-AI/pandas-ai#1223]
### System Info

OS version: win 10 22h2
Python version: 3.12.3
The current version of pandasai being used: 2.1.1

### 🐛 Describe the bug

Originally, these codes were working properly.
But since I specified running parameters such as "open_charts" and "save_charts"<sup>*</sup>, I found that the parameters seemed to be ineffective.
I kept throwing errors afterwards, even deleting all the parameters and deleting the "charts" and "exports" folders(The folder will be rebuilt), but it still didn't work properly.
[car.csv](https://github.com/user-attachments/files/15781120/car.csv)

```python
import pandas as pd
from pandasai import SmartDataframe
from os.path import dirname, join
from os import environ
from datetime import datetime

api_key = environ.get('PANDASAI_API_KEY')
if api_key is None:
    api_key = ''  # todo
    environ.setdefault('PANDASAI_API_KEY', api_key)


base_path = dirname(__file__)
files_path = join(base_path, "files")
csv_path = join(base_path, "car.csv")

data = pd.read_csv(csv_path)
ai_data = SmartDataframe(data)
print('ok')

respone = ai_data.chat('生成马力与油耗关系图？')  # Generate a graph of the relationship between horsepower and fuel consumption?
print(respone)

```

```
Traceback (most recent call last):
  File "D:\anaconda3\envs\zyzs-ai\Lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 310, in run
    ).run(input)
      ^^^^^^^^^^
  File "D:\anaconda3\envs\zyzs-ai\Lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "D:\anaconda3\envs\zyzs-ai\Lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\zyzs-ai\Lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 133, in execute
    {"content_type": "response", "value": ResponseSerializer.serialize(result)},
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\zyzs-ai\Lib\site-packages\pandasai\responses\response_serializer.py", line 35, in serialize
    with open(result["value"], "rb") as image_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Projects/zyzs-ai/exports/charts/temp_chart.png'
Unfortunately, I was not able to answer your question, because of the following error:

[Errno 2] No such file or directory: 'D:/Projects/zyzs-ai/exports/charts/temp_chart.png'
```

<sup>*</sup>Code marked with an asterisk:
```python

ai_df = SmartDataframe(df, config={
                    'open_charts': True,  # or False
                    'save_charts': True,  # or False
                    'save_charts_path': join(project_path, 'exports', 'charts', datetime.now().strftime('%Y-%m-%d')),
                    'enable_cache': False
                })
```

**Comment by wuhuanyan** [comment]
![image](https://github.com/Sinaptik-AI/pandas-ai/assets/39271126/19dba276-7b1e-40de-9dad-47d2bfdd14c3)
```python
import os
import pandas as pd
from pandasai import SmartDataframe
from os.path import dirname, join
from os import environ
from datetime import datetime

api_key = environ.get('PANDASAI_API_KEY')
if api_key is None:
    api_key = ''  # todo
    environ.setdefault('PANDASAI_API_KEY', api_key)

base_path = dirname(__file__)
files_path = join(base_path, "files")
csv_path = join(base_path, files_path, "car.csv")

data = pd.read_csv(csv_path)

# Define the path where you want to save the chart image
save_charts_path = join(base_path, 'exports', 'charts', datetime.now().strftime('%Y-%m-%d'))

# Ensure the directory exists
os.makedirs(save_charts_path, exist_ok=True)

ai_data = SmartDataframe(data)
respone = ai_data.chat('生成马力与油耗关系图？')
print(respone)
```

**Comment by yuxumerkle** [comment]
This is related to issue #1092

**Comment by xuyuanme** [comment]
This is related to issue #1092
