### ISSUE TITLE
Unnecessary datatype mismatch error | Pandas AI

### ISSUE THREAD

**Issue by usmanbinimran-octopus** [Sinaptik-AI/pandas-ai#1231]
### System Info

OS version: Windows 11 pro
Python version: 3.9
The current version of pandasai being used: 2.2

### 🐛 Describe the bug

Hi @gventuri, hope this message finds you well.

I am here with an unexpected behaviour that I am experiencing for so long. Please look into it:

PROMPT
show last 10 records

RESPONSE
Unfortunately, I was not able to answer your question, because of the following error:
Value type <class 'list'> must match with type dataframe

EXPLANATION
I looked at the previous conversation and saw that you wanted to see the last 10 records. So, I wrote some code that takes the last 10 records from each dataset and puts them into a new dataframe. This way, you can easily see the most recent data without having to look through everything.

CLARIFICATION QUESTIONS
['Which dataframe should the last 10 records be shown from?', 'Are the records supposed to be sorted in any particular order before showing the last 10?', 'Is there a specific column that should be used for sorting the records before displaying the last 10?']

REVISED PROMPT:
Display the most recent 10 entries.

EXECUTED CODE:
dfs[0] = dfs[0].tail(10)
dfs[1] = dfs[1].tail(10)
result = {'type': 'dataframe', 'value': dfs}

OPEN AI TOKEN CB:
Tokens Used: 3350
        Prompt Tokens: 2994
        Completion Tokens: 356
Total Cost (USD): $ 0.002031

ERROR ON COMMAND PROMPT:
Traceback (most recent call last):
  File "W:\OctopusTasks\GenInsight\GenInsight-Phase2\GenInsight-Phase2\env-geninsight-phase2\lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 308, in run
    output = (
  File "W:\OctopusTasks\GenInsight\GenInsight-Phase2\GenInsight-Phase2\env-geninsight-phase2\lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "W:\OctopusTasks\GenInsight\GenInsight-Phase2\GenInsight-Phase2\env-geninsight-phase2\lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
  File "W:\OctopusTasks\GenInsight\GenInsight-Phase2\GenInsight-Phase2\env-geninsight-phase2\lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 113, in execute
    raise e
  File "W:\OctopusTasks\GenInsight\GenInsight-Phase2\GenInsight-Phase2\env-geninsight-phase2\lib\site-packages\pandasai\pipelines\chat\code_execution.py", line 97, in execute
    raise InvalidOutputValueMismatch(
pandasai.exceptions.InvalidOutputValueMismatch: Value type <class 'list'> must match with type dataframe
Exception in APILogger: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/log/add</pre>
</body>
</html>

@gventuri,
To the best of my domain knowledge, everything except response is working fine! I think there's a minor case handling that needs to be handled. Because reading at Explanation & Code Executed, everything seems smooth.

Looking forward to hearing from you!

Kind regards,
Usman Bin Imran
+92-310-480-160-1

![image](https://github.com/Sinaptik-AI/pandas-ai/assets/161191241/a8f14081-3ee1-47bd-be5d-aeb56319aea1)

**Comment by usmanbinimran-octopus** [comment]
So it will not work for multiple datasets having different attributes?

Please confirm @gventuri 

Best,
Usman Bin Imran
+92-310-480-160-1
