### ISSUE TITLE
Getting Key error for most use cases in a simple dataframe using open source lama3:8b - instruct model via ollama

### ISSUE THREAD

**Issue by sktg84** [Sinaptik-AI/pandas-ai#1243]
### System Info

Server:
mac m1

Packages:
pandas==1.5.3
pandasai==2.1

Python 3.10.9

### 🐛 Describe the bug

Getting key error for most use cases and its not able to parse dataframes in local llm.

2024-06-20 10:05:10 [ERROR] Failed with error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: 'software_version'

2024-06-20 10:05:10 [ERROR] Pipeline failed on step 6: 'software_version'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 310, in run
    ).run(input)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/code_execution.py", line 113, in execute
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: 'software_version'
2024-06-20 10:05:38 [INFO] HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-06-20 10:05:38 [INFO] Prompt used:

**Comment by sktg84** [comment]
this code is auto gen from llm.

**Comment by sktg84** [comment]
@dosu any updates?
