### ISSUE TITLE
Runtime error: 'python-multipart'

### ISSUE THREAD

**Issue by raminf** [Sinaptik-AI/pandas-ai#1267]
### System Info

- pandas-ai: v2.2.10
- System: Mac M3-Pro Max
- OS: MacOS Sonoma 14.5
- Python: System version 3.12.2
- Docker version: 23.0.6, build ef23cbc
- npm version: 9.7.1
- node version: v20.3.0

### 🐛 Describe the bug

**Summary**: `docker-compose up` of a fresh install fails with  `RuntimeError: Form data requires "python-multipart" to be installed.`

#### Steps

- Downloaded from github. 
- Followed instructions in README to run `docker-compose build`. 
- It failed twice, each time on missing `.env` files. 
- Went into both `server` and `client` directories and figured out that `.env.example` has to be copied to `.env`, although it's not clear what changes have to be made to them.
- Ran `docker-compose build`. This finished.
- Went to run `docker-compose up` and got errors. It was complaining about missing `python-multipart` (see below).
- Ran terminal into the `pandasai-server` container. It looks like `python-multipart` is present in the python packages folder:

```
# pip show python-multipart
Name: python-multipart
Version: 0.0.9
Summary: A streaming multipart parser for Python
Home-page:
Author:
Author-email: Andrew Dunham <andrew@du.nham.ca>
License:
Location: /usr/local/lib/python3.11/site-packages
Requires:
Required-by:
```

- Just to be sure, went into the server/Dockerfile and added an explicit `pip install python-multipart` command.
- Rebuilt, tried to bring it up. Still getting error:

```
❯ docker-compose up
[+] Building 0.0s (0/0)
[+] Running 3/0
 ✔ Container pandas-ai-postgresql-1  Created                               0.0s
 ✔ Container pandabi-frontend        Creat...                              0.0s
 ✔ Container pandabi-backend         Create...                             0.0s
Attaching to pandabi-backend, pandabi-frontend, pandas-ai-postgresql-1
pandas-ai-postgresql-1  |
pandas-ai-postgresql-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
pandas-ai-postgresql-1  |
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.709 UTC [1] LOG:  starting PostgreSQL 14.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.709 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.709 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.711 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pandabi-backend         | startup.sh: line 6: log: command not found
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.718 UTC [22] LOG:  database system was shut down at 2024-07-04 17:39:36 UTC
pandas-ai-postgresql-1  | 2024-07-04 17:41:25.722 UTC [1] LOG:  database system is ready to accept connections
pandabi-frontend        |
pandabi-frontend        | > client@0.1.0 start
pandabi-frontend        | > next start
pandabi-frontend        |
pandabi-frontend        |  ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
pandabi-frontend        |   ▲ Next.js 14.2.3
pandabi-frontend        |   - Local:        http://localhost:3000
pandabi-frontend        |
pandabi-frontend        |  ✓ Starting...
pandabi-frontend        |  ✓ Ready in 218ms
pandabi-backend         | Resolving dependencies...
pandabi-backend         | poetry install
pandabi-backend         | Installing dependencies from lock file
pandabi-backend         |
pandabi-backend         | No dependencies to install or update
pandabi-backend         |
pandabi-backend         | Installing the current project: pandasai-server (0.1.0)
pandabi-backend         |
pandabi-backend         | Warning: The current project could not be installed: No file/folder found for package pandasai-server
pandabi-backend         | If you do not want to install the current project use --no-root.
pandabi-backend         | If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
pandabi-backend         | In a future version of Poetry this warning will become an error!
pandabi-backend         | wait-for-it.sh: 4: shift: can't shift that many
pandabi-backend         | export DEBUG='1'
pandabi-backend         | export ENVIRONMENT='development'
pandabi-backend         | export GPG_KEY='A035C8C19219BA821ECEA86B64E628F8D684696D'
pandabi-backend         | export HOME='/root'
pandabi-backend         | export HOSTNAME='4b0baf1c80d8'
pandabi-backend         | export LANG='C.UTF-8'
pandabi-backend         | export MAKEFLAGS=''
pandabi-backend         | export MAKELEVEL='1'
pandabi-backend         | export MFLAGS=''
pandabi-backend         | export PANDASAI_API_KEY=''
pandabi-backend         | export PATH='/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/bin:/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
pandabi-backend         | export POSTGRES_URL='postgresql+asyncpg://pandasai:password123@postgresql:5432/pandasai-db'
pandabi-backend         | export PS1='(pandasai-server-py3.11) '
pandabi-backend         | export PWD='/app'
pandabi-backend         | export PYTHON_GET_PIP_SHA256='0f8bb2652c0b0965f268312f49ec21e772d421d381af4324beea66b8acf2635c'
pandabi-backend         | export PYTHON_GET_PIP_URL='https://github.com/pypa/get-pip/raw/ac00c61f60b2df101b7cdf90ed319b625ac93b42/public/get-pip.py'
pandabi-backend         | export PYTHON_PIP_VERSION='24.0'
pandabi-backend         | export PYTHON_SETUPTOOLS_VERSION='65.5.1'
pandabi-backend         | export PYTHON_VERSION='3.11.9'
pandabi-backend         | export SHLVL='1'
pandabi-backend         | export SHOW_SQL_ALCHEMY_QUERIES='0'
pandabi-backend         | export TEST_POSTGRES_URL='postgresql+asyncpg://pandasai:password123@postgresql:5432/pandasai-db'
pandabi-backend         | export VIRTUAL_ENV='/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11'
pandabi-backend         | export VIRTUAL_ENV_PROMPT='pandasai-server-py3.11'
pandabi-backend         | export _='/usr/bin/make'
pandabi-backend         | poetry run alembic upgrade head
pandabi-backend         | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
pandabi-backend         | INFO  [alembic.runtime.migration] Will assume transactional DDL.
pandabi-backend         | /
pandabi-backend         | export DEBUG='1'
pandabi-backend         | export ENVIRONMENT='development'
pandabi-backend         | export GPG_KEY='A035C8C19219BA821ECEA86B64E628F8D684696D'
pandabi-backend         | export HOME='/root'
pandabi-backend         | export HOSTNAME='4b0baf1c80d8'
pandabi-backend         | export LANG='C.UTF-8'
pandabi-backend         | export MAKEFLAGS=''
pandabi-backend         | export MAKELEVEL='1'
pandabi-backend         | export MFLAGS=''
pandabi-backend         | export PANDASAI_API_KEY=''
pandabi-backend         | export PATH='/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/bin:/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
pandabi-backend         | export POSTGRES_URL='postgresql+asyncpg://pandasai:password123@postgresql:5432/pandasai-db'
pandabi-backend         | export PS1='(pandasai-server-py3.11) '
pandabi-backend         | export PWD='/app'
pandabi-backend         | export PYTHON_GET_PIP_SHA256='0f8bb2652c0b0965f268312f49ec21e772d421d381af4324beea66b8acf2635c'
pandabi-backend         | export PYTHON_GET_PIP_URL='https://github.com/pypa/get-pip/raw/ac00c61f60b2df101b7cdf90ed319b625ac93b42/public/get-pip.py'
pandabi-backend         | export PYTHON_PIP_VERSION='24.0'
pandabi-backend         | export PYTHON_SETUPTOOLS_VERSION='65.5.1'
pandabi-backend         | export PYTHON_VERSION='3.11.9'
pandabi-backend         | export SHLVL='1'
pandabi-backend         | export SHOW_SQL_ALCHEMY_QUERIES='0'
pandabi-backend         | export TEST_POSTGRES_URL='postgresql+asyncpg://pandasai:password123@postgresql:5432/pandasai-db'
pandabi-backend         | export VIRTUAL_ENV='/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11'
pandabi-backend         | export VIRTUAL_ENV_PROMPT='pandasai-server-py3.11'
pandabi-backend         | export _='/usr/bin/make'
pandabi-backend         | poetry run python main.py
pandabi-backend         | INFO:     Will watch for changes in these directories: ['/app']
pandabi-backend         | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
pandabi-backend         | INFO:     Started reloader process [63] using StatReload
pandabi-backend         | Form data requires "python-multipart" to be installed.
pandabi-backend         | You can install "python-multipart" with:
pandabi-backend         |
pandabi-backend         | pip install python-multipart
pandabi-backend         |
pandabi-backend         | Process SpawnProcess-1:
pandabi-backend         | Traceback (most recent call last):
pandabi-backend         |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
pandabi-backend         |     self.run()
pandabi-backend         |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
pandabi-backend         |     self._target(*self._args, **self._kwargs)
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
pandabi-backend         |     target(sockets=sockets)
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
pandabi-backend         |     return asyncio.run(self.serve(sockets=sockets))
pandabi-backend         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
pandabi-backend         |     return runner.run(main)
pandabi-backend         |            ^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
pandabi-backend         |     return self._loop.run_until_complete(task)
pandabi-backend         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
pandabi-backend         |     return future.result()
pandabi-backend         |            ^^^^^^^^^^^^^^^
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
pandabi-backend         |     config.load()
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 477, in load
pandabi-backend         |     self.loaded_app = import_from_string(self.app)
pandabi-backend         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
pandabi-backend         |     module = importlib.import_module(module_str)
pandabi-backend         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
pandabi-backend         |     return _bootstrap._gcd_import(name[level:], package, level)
pandabi-backend         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
pandabi-backend         |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
pandabi-backend         |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
pandabi-backend         |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
pandabi-backend         |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
pandabi-backend         |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pandabi-backend         |   File "/app/core/server.py", line 10, in <module>
pandabi-backend         |     from api import router
pandabi-backend         |   File "/app/api/__init__.py", line 3, in <module>
pandabi-backend         |     from .v1 import v1_router
pandabi-backend         |   File "/app/api/v1/__init__.py", line 6, in <module>
pandabi-backend         |     from .datasets import datasets_router
pandabi-backend         |   File "/app/api/v1/datasets/__init__.py", line 3, in <module>
pandabi-backend         |     from .datasets import dataset_router
pandabi-backend         |   File "/app/api/v1/datasets/datasets.py", line 27, in <module>
pandabi-backend         |     @dataset_router.post("/")
pandabi-backend         |      ^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 657, in decorator
pandabi-backend         |     self.add_api_route(
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 596, in add_api_route
pandabi-backend         |     route = route_class(
pandabi-backend         |             ^^^^^^^^^^^^
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 452, in __init__
pandabi-backend         |     self.body_field = get_body_field(dependant=self.dependant, name=self.unique_id)
pandabi-backend         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 766, in get_body_field
pandabi-backend         |     check_file_field(final_field)
pandabi-backend         |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 111, in check_file_field
pandabi-backend         |     raise RuntimeError(multipart_not_installed_error) from None
pandabi-backend         | RuntimeError: Form data requires "python-multipart" to be installed.
pandabi-backend         | You can install "python-multipart" with:
pandabi-backend         |
pandabi-backend         | pip install python-multipart
pandabi-backend         |
```

**Comment by raminf** [comment]
Wow. Was ready to write-off the bot response. But it actually nailed it!   :-)

Added `python-multipart = "^0.0.9"` to the pyproject.toml file in both the root and the server directories. Then rebuilt it and the system did come up.

However, nothing seems to work on the back-end. Tried to get an API key from pandas-ai, but the website has issues with account sign-up flow (not getting any verification emails). Will try again in a few days. Also, that's a different issue, so closing this one.
