### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get

### ISSUE THREAD

**Issue by justbane** [Sinaptik-AI/pandas-ai#1316]
### System Info

pandasai version 2.2.14

### 🐛 Describe the bug

Using this simple code where ‘file_path’ is the path to the CSV file and ‘query’ is the text query to run
```sdf = SmartDataframe(file_path, config={"llm": llm, "conversational": False}, description=ds.description)
            query_result = sdf.chat(query, output_type=['plot','string','number'])
            print(query_result) 
```

I receive the answer but I also get an error from the code. specifically on:
```
File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/helpers/output_validator.py", line 31, in validate
    result_type, result_value = result.get("type"), result.get("value")
                                ^^^^^^^^^^
```

Not sure what is happening - here is more from the pandaai.log file
```
2024-08-07 15:49:45 [ERROR] Pipeline failed on step 6: 'list' object has no attribute 'get'
2024-08-07 15:49:45 [WARNING] Bad Request: /query/11
2024-08-07 15:51:53 [INFO] /workspaces/research-data/app/views/query.py changed, reloading.
```

**Comment by justbane** [comment]
I tried adjusting the code, including removing the output_type attirbute on the chat method. I still recive an error but this time it is different.

```
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 335, in run
    ).run(input)
      ^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 113, in execute
    raise e
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 96, in execute
    if not OutputValidator.validate_result(result):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandasai/helpers/output_validator.py", line 73, in validate_result
    raise InvalidOutputValueMismatch(
pandasai.exceptions.InvalidOutputValueMismatch: Result must be in the format of dictionary of type and value
cannot access local variable 'df' where it is not associated with a value
```

**Comment by justbane** [comment]
I do not control the response from the LLM so I should not have to convert anything… this is using standard code from the examples… why is it failing? This seems to be a bug as I am doing this in a try/catch and it always throws an exception.
