### ISSUE TITLE
Code Generated & Code Cleaning is not correct 

### ISSUE THREAD

**Issue by fazri02** [Sinaptik-AI/pandas-ai#1324]
### System Info

Version: 2.2.14

Eliminates import library code when the code appears with lots of spaces in front of it even though the code is needed

### 🐛 Describe the bug

2024-08-08 17:22:49 [INFO] Code generated:
            ```
"""            import seaborn as sns"""
import matplotlib.pyplot as plt

df = dfs[0][dfs[0]['year'] == 2023]
df = df.groupby(['direct_cause_category', 'equipment', 'plant'])['loss_pvc'].sum().reset_index()
plt.figure(figsize=(15, 10))
sns.barplot(data=df, x='direct_cause_category', y='loss_pvc', hue='equipment', palette='Set3')
plt.xticks(rotation=90)
plt.title('Total Loss by Direct Cause, Equipment, and Plant in 2023')
plt.xlabel('Direct Cause Category')
plt.ylabel('Loss (PVC)')
plt.legend(title='Equipment')
plt.tight_layout()
plt.savefig('exports/charts/46f15da9-d530-4955-ab0b-d0d564046f9e.png')
result = {'type': 'plot', 'value': 'exports/charts/46f15da9-d530-4955-ab0b-d0d564046f9e.png'}

2024-08-08 17:22:49 [ERROR] Failed with error: Traceback (most recent call last):
  File "/root/virtualenv/Streamlit-ai/lib64/python3.9/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
  File "/root/virtualenv/Streamlit-ai/lib64/python3.9/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 4, in <module>
NameError: name 'sns' is not defined

**Comment by fazri02** [comment]
Dear @dosu 
my case the code is generated by LLM, what your recommendation ?

**Comment by fazri02** [comment]
i can't put this config, always return error = 1 validation error for Config custom_whitelisted_dependencies -> 0 str type expected (type=type_error.str)

config = {
    "custom_whitelisted_dependencies": {
        "seaborn": "sns",
        "matplotlib.pyplot": "plt"
    }
}

**Comment by fazri02** [comment]
how to add import seaborn as sns
