### ISSUE TITLE
use openai error(openai.BadRequestError: Error code: 400)

### ISSUE THREAD

**Issue by XiaozhiAGI** [Sinaptik-AI/pandas-ai#1365]
### System Info

Unfortunately, I was not able to answer your question, because of the following error:

Error code: 400 - {'object': 'error', 'message': 'Conversation roles must alternate user/assistant/user/assistant/...', 'type': 'BadRequestError', 'param': None, 'code': 400}

Traceback (most recent call last):
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 335, in run
    ).run(input)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\pipelines\chat\code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\llm\base.py", line 201, in generate_code
    response = self.call(instruction, context)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\llm\base.py", line 391, in call
    self.chat_completion(self.last_prompt, memory)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\pandasai\llm\base.py", line 365, in chat_completion
    response = self.client.create(**params)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\openai\_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\openai\_base_client.py", line 902, in request
    return self._request(
  File "E:\users\xxx\.conda\envs\llm_new\lib\site-packages\openai\_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Conversation roles must alternate user/assistant/user/assistant/...', 'type': 'BadRequestError', 'param': None, 'code': 400}

### 🐛 Describe the bug

Error code: 400 - {'object': 'error', 'message': 'Conversation roles must alternate user/assistant/user/assistant/...', 'type': 'BadRequestError', 'param': None, 'code': 400}

**Comment by 52phm** [comment]
The source code is the same as the code you provided, which can solve openai What is the replacement code for BadRequestError?

**Comment by 52phm** [comment]
No effect, still reporting the same error
