### ISSUE TITLE
Problem with installing with docker on macos

### ISSUE THREAD

**Issue by kaziu007** [Sinaptik-AI/pandas-ai#1368]
### System Info

version 2.2.14, macos, python 3.11

During installation i have following issue:

6.516 
6.516   ChefBuildError
6.516 
6.516   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
6.516   
6.516   running egg_info
6.516   writing psycopg2.egg-info/PKG-INFO
6.516   writing dependency_links to psycopg2.egg-info/dependency_links.txt
6.516   writing top-level names to psycopg2.egg-info/top_level.txt
6.516   
6.516   Error: pg_config executable not found.
6.516   
6.516   pg_config is required to build psycopg2 from source.  Please add the directory
6.516   containing pg_config to the $PATH or specify the full executable path with the
6.516   option:
6.516   
6.516       python setup.py build_ext --pg-config /path/to/pg_config build ...
6.516   
6.516   or with the pg_config option in 'setup.cfg'.
6.516   
6.516   If you prefer to avoid building psycopg2 from source, please install the PyPI
6.516   'psycopg2-binary' package instead.
6.516   
6.516   For further information please check the 'doc/src/install.rst' file (also at
6.516   <https://www.psycopg.org/docs/install.html>).
6.516   
6.516   
6.516 
6.516   at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
6.520       160│ 
6.520       161│                 error = ChefBuildError("\n\n".join(message_parts))
6.520       162│ 
6.520       163│             if error is not None:
6.520     → 164│                 raise error from None
6.520       165│ 
6.520       166│             return path
6.520       167│ 
6.520       168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
6.520 
6.520 Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "psycopg2 (==2.9.9)"'.
6.520 
6.629 Warning: The file chosen for install of matplotlib 3.9.1 (matplotlib-3.9.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl) is yanked. Reason for being yanked: The Windows wheels, under some conditions, caused segfaults in unrelated user code.  Due to this we deleted the Windows wheels to prevent these segfaults, however this caused greater disruption as pip then began to try (and fail) to build 3.9.1 from the sdist on Windows which impacted far more users.  Yanking the whole release is the only tool available to eliminate these failures without changes to on the user side.  The sdist, OSX wheel, and manylinux wheels are all functional and there are no critical bugs in the release.   Downstream packagers should not yank their builds of Matplotlib 3.9.1.  See https://github.com/matplotlib/matplotlib/issues/28551 for details.
------
failed to solve: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1

-----------

I have tried all the solutions form previous reports of that bug, but nothing works in macos. How to fix that on macos? what changes to the dockerfile/pyproject.toml are needed? It looks like my psycopg2 is visible in the environment, path is exported, still it fails with the same error.

### 🐛 Describe the bug

Installation with  docker-compose build  is failing.

**Comment by kaziu007** [comment]
This has been solved. Thank you.

Now I am facing following error: .21 TypeError: Failed to parse URL from undefined/v1/datasets/
26.21     at new Request (node:internal/deps/undici/undici:6949:19)
26.21     at a (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:180691)
26.21     ... 3 lines matching cause stack trace ...
26.21     at async p (/app/build/server/app/settings/workspaces/addspaces/page.js:1:12080) {
26.21   digest: '2806050886',
26.21   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
26.21       at new NodeError (node:internal/errors:399:5)
26.21       at URL.onParseError (node:internal/url:565:9)
26.21       at new URL (node:internal/url:645:5)
26.21       at new Request (node:internal/deps/undici/undici:6947:25)
26.21       at a (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:180691)
26.21       at B (/app/build/server/chunks/948.js:2:6846)
26.21       at /app/build/server/chunks/948.js:2:9092
26.21       at async n (/app/build/server/app/settings/workspaces/addspaces/page.js:1:15050)
26.21       at async p (/app/build/server/app/settings/workspaces/addspaces/page.js:1:12080) {
26.21     input: 'undefined/v1/datasets/',
26.21     code: 'ERR_INVALID_URL'

**Comment by kaziu007** [comment]
how do i get the correct API URL?

**Comment by kaziu007** [comment]
shall i use that url: https://your-api-base-url.com n the env variables? ot i shall get the real one somehow?

**Comment by kaziu007** [comment]
I have tried with
NEXT_PUBLIC_API_URL=http://server:8000/ and NEXT_PUBLIC_API_URL=http://localhost:8000/

but none is working

**Comment by kaziu007** [comment]
i have now following error:
25.50 TypeError: fetch failed
25.50     at Object.fetch (node:internal/deps/undici/undici:14152:11)
25.50     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25.50     at async n (/app/build/server/app/settings/workspaces/addspaces/page.js:1:15050)
25.50     at async p (/app/build/server/app/settings/workspaces/addspaces/page.js:1:12080) {
25.50   cause: Error: getaddrinfo ENOTFOUND server
25.50       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
25.50       at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
25.50     errno: -3008,
25.50     code: 'ENOTFOUND',
25.50     syscall: 'getaddrinfo',
25.50     hostname: 'server'
25.50   },
25.50   digest: '3287353831'
25.50 }
