### ISSUE TITLE
Error when installing with docker

### ISSUE THREAD

**Issue by kaziu007** [Sinaptik-AI/pandas-ai#1369]
### System Info

2.2.14, macos

### 🐛 Describe the bug

I get following issue when installing with docker:
.06 }
27.06 Get request failed TypeError: fetch failed
27.06     at Object.fetch (node:internal/deps/undici/undici:14152:11)
27.06     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
27.06     at async i (/app/build/server/app/settings/workspaces/editspaces/page.js:1:13704)
27.06     at async p (/app/build/server/app/settings/workspaces/addspaces/page.js:1:12080) {
27.06   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
27.06       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
27.06       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
27.06     errno: -111,
27.06     code: 'ECONNREFUSED',
27.06     syscall: 'connect',
27.06     address: '127.0.0.1',
27.06     port: 8000
27.06   }
27.06 }
27.06 TypeError: fetch failed
27.06     at Object.fetch (node:internal/deps/undici/undici:14152:11)
27.06     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
27.06     at async i (/app/build/server/app/settings/workspaces/editspaces/page.js:1:13704)
27.06     at async p (/app/build/server/app/settings/workspaces/addspaces/page.js:1:12080) {
27.06   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
27.06       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
27.06       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
27.06     errno: -111,
27.06     code: 'ECONNREFUSED',
27.06     syscall: 'connect',
27.06     address: '127.0.0.1',
27.06     port: 8000
27.06   },
27.06   digest: '2837704541'
27.06 }

**Comment by kaziu007** [comment]
I have NEXT_PUBLIC_API_URL='http://localhost:8000/'

still i get:
26.99 TypeError: fetch failed
26.99     at Object.fetch (node:internal/deps/undici/undici:14152:11)
26.99     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
26.99     at async n (/app/build/server/app/settings/workspaces/addspaces/page.js:1:15050)
26.99     at async u (/app/build/server/app/settings/datasets/page.js:1:8848) {
26.99   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
26.99       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
26.99       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
26.99     errno: -111,
26.99     code: 'ECONNREFUSED',
26.99     syscall: 'connect',
26.99     address: '127.0.0.1',
26.99     port: 8000
26.99   },
26.99   digest: '67092955'
26.99 }

**Comment by kaziu007** [comment]
@dosu please name all the files in which i shall place the https://localhost. it seems so far that the setup is failing on 127.0.0.1 while i have set 

6.10 }
26.10 TypeError: fetch failed
26.10     at Object.fetch (node:internal/deps/undici/undici:14152:11)
26.10     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
26.10     at async i (/app/build/server/app/settings/datasets/page.js:1:13460)
26.10     at async u (/app/build/server/app/settings/datasets/page.js:1:8848) {
26.10   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
26.10       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
26.10       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
26.10     errno: -111,
26.10     code: 'ECONNREFUSED',
26.10     syscall: 'connect',
26.10     address: '127.0.0.1',
26.10     port: 8000
26.10   },
26.10   digest: '4039937587'
26.10 }

**Comment by kaziu007** [comment]
@doku
I have client/.env
NEXT_PUBLIC_API_URL='http://localhost:8000/'

I have server/.env
SERVER_HOST=localhost

I have server/core/config.py i have 
"postgresql+asyncpg://user:password@localhost:5432/db-name"

Still the error message is:
28.96 }
28.96 TypeError: fetch failed
28.96     at Object.fetch (node:internal/deps/undici/undici:14152:11)
28.96     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
28.96     at async i (/app/build/server/app/settings/workspaces/editspaces/page.js:1:13704)
28.96     at async p (/app/build/server/app/settings/workspaces/editspaces/page.js:1:12135) {
28.96   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
28.96       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
28.96       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
28.96     errno: -111,
28.96     code: 'ECONNREFUSED',
28.96     syscall: 'connect',
28.96     address: '127.0.0.1',
28.96     port: 8000
28.96   },
28.96   digest: '711901359'
28.96 }

Which other file i shall update?

**Comment by kaziu007** [comment]
@dosu
I have client/.env
NEXT_PUBLIC_API_URL='http://localhost:8000/'

I have server/.env
SERVER_HOST=localhost

I have server/core/config.py i have
"postgresql+asyncpg://user:password@localhost:5432/db-name"

Still the error message is:
28.96 }
28.96 TypeError: fetch failed
28.96 at Object.fetch (node:internal/deps/undici/undici:14152:11)
28.96 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
28.96 at async i (/app/build/server/app/settings/workspaces/editspaces/page.js:1:13704)
28.96 at async p (/app/build/server/app/settings/workspaces/editspaces/page.js:1:12135) {
28.96 cause: Error: connect ECONNREFUSED 127.0.0.1:8000
28.96 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
28.96 at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
28.96 errno: -111,
28.96 code: 'ECONNREFUSED',
28.96 syscall: 'connect',
28.96 address: '127.0.0.1',
28.96 port: 8000
28.96 },
28.96 digest: '711901359'
28.96 }

Which other file i shall update?

**Comment by kaziu007** [comment]
@dosu 
It looks like the backend is not starting up. I check all the files and it is correct. Shall i update the 127.0.0.1 to local host in all occurences?

**Comment by kaziu007** [comment]
@dosu 

I have following message:
raceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

**Comment by kaziu007** [comment]
@dosu 
Now i have following error:
  File "/app/main.py", line 7, in <module>
    from core.config import config
  File "/app/core/config.py", line 3, in <module>
    from pydantic import BaseSettings, PostgresDsn
  File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 402, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.9/migration/#basesettings-has-moved-to-pydantic-settings for more details.

**Comment by kaziu007** [comment]
@dosu 
For code 
if __name__ == "__main__":
    uvicorn.run(
        app="core.server:app",
        reload=True if config.ENVIRONMENT != "production" else False,
        host=os.environ.get("SERVER_HOST", "0.0.0.0"),
        port=os.environ.get("SERVER_PORT", 8000),
        workers=1,
    )

I have error ERROR:    Error loading ASGI app. Could not import module "app.main".

what is the correct code to start it?

**Comment by kaziu007** [comment]
@dosu 
the code is following:
if __name__ == "__main__":
    uvicorn.run(
        app="core.server:app",
        reload=True if config.ENVIRONMENT != "production" else False,
        host=os.environ.get("SERVER_HOST", "0.0.0.0"),
        port=os.environ.get("SERVER_PORT", 8000),
        workers=1,
    )

Problem persists:
WARNING:  StatReload detected changes in 'main.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "app.main".
