### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by vsneelesh** [Sinaptik-AI/pandas-ai#1380]
I am unable to use clarification_quetions(query) function. I have been using this so that the user can give an input if anything needed. 
But from today morning am getting this error 
Traceback (most recent call last):
  File "/home/neelesh/chatwithcsv_v6/app.py", line 44, in <module>
    if agent.clarification_questions(query):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/agent/base.py", line 420, in clarification_questions
    result = self.call_llm_with_prompt(prompt)
  File "/usr/local/lib/python3.10/dist-packages/pandasai/agent/base.py", line 227, in call_llm_with_prompt
    raise InvalidLLMOutputType("Response validation failed!")
pandasai.exceptions.InvalidLLMOutputType: Response validation failed!

This is what I am using questions=agent.clarification_questions(query)

for question in questions:
        print(question). Could you clarify on this if there was any update or something similar

Though it was working fine from sometime today.

**Comment by vsneelesh** [comment]
I tried the code I gave you previously. It was working fine but rn the code
is not working. Anyway when i had checked the docs initially it was
agent.clarification_questions not agent.clarification_question . An s is
removed . I would like to ask if there was some changes made in the docs
