### ISSUE TITLE
Chat raise a `KeyError: 'file_path'` exception after upload my csv data file

### ISSUE THREAD

**Issue by xyb** [Sinaptik-AI/pandas-ai#1383]
### System Info

OS: macOS 14.4 23E214 arm64
Python: 3.11
pandasai: v2.2.15

### 🐛 Describe the bug

Got `Network Error` when interacting with pandasai in browser after start with `docker-compose up` and upload my csv data file. Error logs:
```
pandabi-backend   | INFO:     172.17.0.1:54250 - "POST /v1/chat/ HTTP/1.1" 500 Internal Server Error
pandabi-backend   | ERROR:    Exception in ASGI application
pandabi-backend   | Traceback (most recent call last):
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
pandabi-backend   |     result = await app(  # type: ignore[func-returns-value]
pandabi-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
pandabi-backend   |     return await self.app(scope, receive, send)
pandabi-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
pandabi-backend   |     await super().__call__(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 118, in __call__
pandabi-backend   |     await self.middleware_stack(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
pandabi-backend   |     raise exc
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
pandabi-backend   |     await self.app(scope, receive, _send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
pandabi-backend   |     await self.simple_response(scope, receive, send, request_headers=headers)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
pandabi-backend   |     await self.app(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 48, in __call__
pandabi-backend   |     await self.app(scope, receive, send)
pandabi-backend   |   File "/app/core/fastapi/middlewares/sqlalchemy.py", line 19, in __call__
pandabi-backend   |     raise exception
pandabi-backend   |   File "/app/core/fastapi/middlewares/sqlalchemy.py", line 17, in __call__
pandabi-backend   |     await self.app(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
pandabi-backend   |     raise exc
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
pandabi-backend   |     await self.app(scope, receive, sender)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
pandabi-backend   |     raise e
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
pandabi-backend   |     await self.app(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
pandabi-backend   |     await route.handle(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
pandabi-backend   |     await self.app(scope, receive, send)
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
pandabi-backend   |     response = await func(request)
pandabi-backend   |                ^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
pandabi-backend   |     raw_response = await run_endpoint_function(
pandabi-backend   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/root/.cache/pypoetry/virtualenvs/pandasai-server-9TtSrW0h-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
pandabi-backend   |     return await dependant.call(**values)
pandabi-backend   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/app/api/v1/chat/chat.py", line 20, in chat
pandabi-backend   |     response = await chat_controller.chat(user, chat_request)
pandabi-backend   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/app/core/database/transactional.py", line 40, in decorator
pandabi-backend   |     raise exception
pandabi-backend   |   File "/app/core/database/transactional.py", line 21, in decorator
pandabi-backend   |     result = await self._run_required(
pandabi-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/app/core/database/transactional.py", line 47, in _run_required
pandabi-backend   |     result = await function(*args, **kwargs)
pandabi-backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pandabi-backend   |   File "/app/app/controllers/chat.py", line 76, in chat
pandabi-backend   |     df = pd.read_csv(config["file_path"])
pandabi-backend   |                      ~~~~~~^^^^^^^^^^^^^
pandabi-backend   | KeyError: 'file_path'
```

**Comment by xyb** [comment]
I add a debug print of config var:
```
pandabi-backend   | {'file_path': '/app/core/../data/Loan payments data.csv', 'file_name': 'Loan payments data.csv'}
pandabi-backend   | {}
```

The dataset I uploaded has a empty config dict.
