### ISSUE TITLE
TypeError: e?.map is not a function

### ISSUE THREAD

**Issue by tangfei** [Sinaptik-AI/pandas-ai#1392]
### System Info

pandasai:2.2.15
python:3.12.4
masos

### 🐛 Describe the bug

```
> client@0.1.0 build
> next build

  ▲ Next.js 14.2.15
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
 ✓ Checking validity of types
 ✓ Collecting page data
   Generating static pages (7/15)  [=   ]TypeError: e?.map is not a function
    at c (/Users/tom_tang/Projects/pandas-ai/client/build/server/app/settings/workspaces/page.js:1:10168)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '3282278517'
}
TypeError: e?.map is not a function
    at c (/Users/tom_tang/Projects/pandas-ai/client/build/server/app/settings/workspaces/page.js:1:10168)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '3282278517'
}

Error occurred prerendering page "/settings/workspaces". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: e?.map is not a function
    at c (/Users/tom_tang/Projects/pandas-ai/client/build/server/app/settings/workspaces/page.js:1:10168)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ✓ Generating static pages (15/15)

> Export encountered errors on following paths:
	/settings/workspaces/page: /settings/workspaces
```

**Comment by tangfei** [comment]
I change client Dockerfile 
```
FROM node:19.4.0-alpine3.17

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
```

now the result is:
```
ERROR [client 6/6] RUN npm run build                                                                                                                                                                      40.2s
------
 > [client 6/6] RUN npm run build:
0.553
0.553 > client@0.1.0 build
0.553 > next build
0.553
1.204 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.204 This information is used to shape Next.js' roadmap and prioritize features.
1.205 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.205 https://nextjs.org/telemetry
1.205
1.271   ▲ Next.js 14.2.15
1.271   - Environments: .env
1.271
1.331    Creating an optimized production build ...
31.79  ✓ Compiled successfully
31.79    Skipping linting
31.79    Checking validity of types ...
36.62    Collecting page data ...
38.41    Generating static pages (0/15) ...
38.64    Generating static pages (3/15)
38.74 Get request failed TypeError: fetch failed
38.74     at Object.fetch (node:internal/deps/undici/undici:14152:11)
38.74     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
38.74     at async a (/app/build/server/app/(ee)/settings/logs/page.js:39:10791)
38.74     at async i (/app/build/server/app/(ee)/settings/logs/page.js:39:9587) {
38.74   cause: Error: connect ECONNREFUSED ::1:8000
38.74       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
38.74       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
38.74     errno: -111,
38.74     code: 'ECONNREFUSED',
38.74     syscall: 'connect',
38.74     address: '::1',
38.74     port: 8000
38.74   }
38.74 }
```
