### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ninalty** [Sinaptik-AI/pandas-ai#1398]
Path: /intro

After using 'pip install pandasai', import pandasai in python send me back error. I tried python 3.9, 3.10. 3.11 and 3.12. Same error.
Also, can't join the discord group through the link provided.

here is the error message:
>>> import pandasai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandasai/__init__.py", line 6, in <module>
    from pandasai.smart_dataframe import SmartDataframe
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandasai/smart_dataframe/__init__.py", line 26, in <module>
    import pandasai.pandas as pd
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandasai/pandas/__init__.py", line 13, in <module>
    from pandas import *
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/opt/miniconda3/envs/myenv2/lib/python3.11/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by ninalty** [comment]
Thanks. It works
