### ISSUE TITLE
ModuleNotFoundError: No module named 'seaborn'

### ISSUE THREAD

**Issue by desertproject** [Sinaptik-AI/pandas-ai#1439]
### System Info

OS version: `Debian GNU/Linux 12 (bookworm)`
Python version: `Python 3.11.2`
The current version of pandasai being used: `2.4.0`

### 🐛 Describe the bug

When instantiating a new Agent, the following error occurs, indicating that **seaborn** should not be an optional dependency:

```
Traceback (most recent call last):
  File ".../streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File ".../streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File ".../app.py", line 1, in <module>
    from pandasai import Agent
  File ".../pandasai/__init__.py", line 6, in <module>
    from pandasai.smart_dataframe import SmartDataframe
  File ".../pandasai/smart_dataframe/__init__.py", line 27, in <module>
    from pandasai.agent import Agent
  File ".../pandasai/agent/__init__.py", line 1, in <module>
    from .agent import Agent
  File ".../pandasai/agent/agent.py", line 5, in <module>
    from pandasai.agent.base import BaseAgent
  File ".../pandasai/agent/base.py", line 8, in <module>
    from pandasai.agent.base_security import BaseSecurity
  File ".../pandasai/agent/base_security.py", line 2, in <module>
    from pandasai.pipelines.pipeline import Pipeline
  File ".../pandasai/pipelines/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File ".../pandasai/pipelines/pipeline.py", line 5, in <module>
    from pandasai.config import load_config_from_json
  File ".../pandasai/config.py", line 4, in <module>
    from . import llm
  File ".../pandasai/llm/__init__.py", line 5, in <module>
    from .google_gemini import GoogleGemini
  File ".../pandasai/llm/google_gemini.py", line 16, in <module>
    from ..helpers.optional import import_dependency
  File ".../pandasai/helpers/optional.py", line 22, in <module>
    from pandasai.safe_libs.restricted_seaborn import RestrictedSeaborn
  File ".../pandasai/safe_libs/restricted_seaborn.py", line 1, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
```

After installing **seaborn** using `poetry add seaborn`, the following error occurs, indicating that **pyyaml** is also required:

```
Traceback (most recent call last):
  File ".../streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File ".../streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File ".../app.py", line 1, in <module>
    from pandasai import Agent
  File ".../pandasai/__init__.py", line 6, in <module>
    from pandasai.smart_dataframe import SmartDataframe
  File ".../pandasai/smart_dataframe/__init__.py", line 27, in <module>
    from pandasai.agent import Agent
  File ".../pandasai/agent/__init__.py", line 1, in <module>
    from .agent import Agent
  File ".../pandasai/agent/agent.py", line 5, in <module>
    from pandasai.agent.base import BaseAgent
  File ".../pandasai/agent/base.py", line 8, in <module>
    from pandasai.agent.base_security import BaseSecurity
  File ".../pandasai/agent/base_security.py", line 2, in <module>
    from pandasai.pipelines.pipeline import Pipeline
  File ".../pandasai/pipelines/__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File ".../pandasai/pipelines/pipeline.py", line 5, in <module>
    from pandasai.config import load_config_from_json
  File ".../pandasai/config.py", line 6, in <module>
    from .schemas.df_config import Config
  File ".../pandasai/schemas/df_config.py", line 4, in <module>
    from pandasai.helpers.dataframe_serializer import DataframeSerializerType
  File ".../pandasai/helpers/dataframe_serializer.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

To resolve this, I had to run `poetry add pyyaml`, and then everything worked correctly.

### Suggestion

1. **Make seaborn a required dependency**: It appears that **seaborn** is being imported without being marked as a required dependency, causing errors when it's missing. It should either be made a required dependency or a check should be added to verify if it is present in the environment before importing.

2. **Make pyyaml a required dependency**: Similarly, **pyyaml** should be listed as a required dependency, as it is necessary for proper functionality.

**Comment by gdcsinaptik** [comment]
Thanks for noticing @desertproject. Closing the ticket as pull request https://github.com/Sinaptik-AI/pandas-ai/pull/1500 deals with it
