### ISSUE TITLE
NameError: name 'eval' is not defined

### ISSUE THREAD

**Issue by JunaidHassanCB** [Sinaptik-AI/pandas-ai#758]
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
ERROR:pandasai.helpers.logger:Failed with error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 438, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 286, in execute_code
    return analyze_data(self._get_originals(dfs))
  File "<string>", line 21, in analyze_data
NameError: name 'eval' is not defined
. Retrying

**Comment by anitaokoh** [comment]
did you get a response for this
