### ISSUE TITLE
ImportError: __import__ not found

### ISSUE THREAD

**Issue by clz960630** [Sinaptik-AI/pandas-ai#802]
### System Info

Pandasai：1.5.5

### 🐛 Describe the bug

When LLM gives code with 'import',e.g. import re, PANDASAI code runner always returns this error information:
'ImportError: \_\_import\_\_ not found'
I wonder what causes this problem and how to fix it.

**Comment by gventuri** [comment]
@clz960630 can you share the logs or the prompt you are using?
It seems to be a problem related to a non-whitelisted library, but I think the logs might provide a lot more info!

**Comment by clz960630** [comment]
> @clz960630 can you share the logs or the prompt you are using? It seems to be a problem related to a non-whitelisted library, but I think the logs might provide a lot more info!

2023-12-11 12:36:38 [INFO] Question: Cavaliers是哪个城市的球队？
2023-12-11 12:36:38 [INFO] Running PandasAI with langchain_custom LLM...
2023-12-11 12:36:38 [INFO] Prompt ID: f42cd6df-e361-43d8-ba34-5dc40c61250a
2023-12-11 12:36:38 [INFO] Executing Step 0: CacheLookup
2023-12-11 12:36:38 [INFO] Executing Step 1: PromptGeneration
2023-12-11 12:36:38 [INFO] Using prompt: 

```
你是一位高级数据分析师，给你如下“dataframe”和“用户提问”:

<dataframe>
dfs[0]:565x10
Name,Birthday,Country,Height,Weight,Played_Season,Jersey_Number,Position,Team,City_of_Team
Bam Adebayo,1997-07-18,USA,205,114,6,13.0,Center,Heat,Miami
Steven Adams,1993-07-20,New Zealand,210,119,10,4.0,Center,Grizzlies,Memphis
Precious Achiuwa,1999-09-19,Nigeria,203,101,3,5.0,Forward,Raptors,Toronto
</dataframe>

<用户提问>
请用中文回答以下问题：
Q: Cavaliers是哪个城市的球队？
</用户提问>

你的任务是修改下面的“初始代码”，使其能够在“dataframe”中得到“用户提问”的答案。

<初始代码>
#这是初始python函数，不要修改函数analyze_data的参数和现有代码，不要在函数外添加任何代码。

def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    result = dict()
    result['type'] = 'string'
    df = dfs[0]
    """
    请在此处按照如下步骤，针对用户给你的dataframes (`dfs`)分析数据并补全此函数，完成用户的要求或提问。
    0. 首先先将pandas库以外的必要的python库在此处import进来。
    1. 明确用户需求，确定其需要访问的列。在查询表格时请使用如下“列名”：Name ; Birthday ; Country ; Height ; Weight ; Played_Season ; Jersey_Number ; Position ; Team ; City_of_Team
    2. 处理数据。
    4. （只有用户要求绘制图表才执行此步骤）如果用户要求绘制图表，请使用matplotlib库以宋体字体生成图片并保存为temp_chart.png，不要显示图片。在Matplotlib中请使用Times New Roman字体。将生成图片的路径赋值给result里的value。
    5. 返回一个包含如下内容的dict（即result变量）:
    - type (变量类型：string，变量值：'string')
    - value (变量类型：string)
    """
    return result
</初始代码>

先深呼吸，然后一步步推理，根据“用户提问”修改“初始代码”，输出你修改后的analyze_data函数，不要输出其他内容。
 ```
2023-12-11 12:36:38 [INFO] Executing Step 2: CodeGenerator
2023-12-11 12:37:30 [INFO] Code generated:
 ```
 def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    result = dict()
    result['type'] = 'string'
    df = dfs[0]
    # 请在此处按照如下步骤，针对用户给你的dataframes (`dfs`)分析数据并补全此函数，完成用户的要求或提问。
    # 0. 首先先将pandas库以外的必要的python库在此处import进来。
    import matplotlib.pyplot as plt
    import numpy as np
    # 1. 明确用户需求，确定其需要访问的列。
    df_team = df[df['Team'].str.contains('Cavaliers')]
    team_city = df_team.iloc[0]['City_of_Team']
    # 2. 处理数据。
    # 3. 处理用户需求。
    # 4. （只有用户要求绘制图表才执行此步骤）如果用户要求绘制图表，请使用matplotlib库以宋体字体生成图片并保存为temp_chart.png，不要显示图片。在Matplotlib中请使用Times New Roman字体。将生成图片的路径赋值给result里的value。
    # 5. 返回一个包含如下内容的dict（即result变量）:
    # - type (变量类型：string，变量值：'string')
    # - value (变量类型：string)
    result['value'] = f'Cavaliers是来自{team_city}的球队。'
    return result
result = analyze_data(dfs)
 ```
      
2023-12-11 12:37:30 [INFO] Executing Step 3: CachePopulation
2023-12-11 12:37:30 [INFO] Executing Step 4: CodeExecution
2023-12-11 12:37:30 [INFO] Saving charts to /work/home/project/Table_qa/exports/charts/temp_chart.png
2023-12-11 12:37:30 [INFO] 
Code running:
```  
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    result = dict()
    result['type'] = 'string'
    df = dfs[0]
    import matplotlib.pyplot as plt
    import numpy as np
    df_team = df[df['Team'].str.contains('Cavaliers')]
    team_city = df_team.iloc[0]['City_of_Team']
    result['value'] = f'Cavaliers是来自{team_city}的球队。'
    return result

result = analyze_data(dfs)
 ```

2023-12-11 12:37:30 [WARNING] Failed to execute code with a correction framework [retry number: 1]
2023-12-11 12:37:30 [ERROR] Failed with error: Traceback (most recent call last):
```
  File "/usr/local/lib/python3.9/dist-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/usr/local/lib/python3.9/dist-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pandasai/helpers/code_manager.py", line 203, in execute_code
    exec(code_to_run, environment)
  File "<string>", line 13, in <module>
  File "<string>", line 5, in analyze_data
ImportError: __import__ not found
```

**Comment by 0gur1** [comment]
Hi, did u solve the problem?
