### ISSUE TITLE
Langchain LLM

### ISSUE THREAD

**Issue by danielstankw** [Sinaptik-AI/pandas-ai#834]
### System Info

Python: 3.10.6
Pandasai: 1.5.11

### 🐛 Describe the bug

I have to replace some log info for privacy reasons.

```py
from langchain.llms import OpenAI

custom_llm = OpenAI(model=<MODEL_NAME>",
        api_key=<API KEY>",
        base_url=<URL>,
        verbose=True,
        temperature=0.0)
   
df_smart = SmartDataframe('data2.csv', config={"llm":custom_llm, 
                                              "verbose":True})    
        
response = df_smart.chat('Return maximal amount')
```

After this the log outputs

```
2023-12-22 08:41:32 [INFO] Question: Return maximal amount
2023-12-22 08:41:32 [INFO] Running PandasAI with langchain_openai LLM...
2023-12-22 08:41:32 [INFO] Prompt ID <ID>
2023-12-22 08:41:32 [INFO] Executing Step 0: CacheLookup
2023-12-22 08:41:32 [INFO] Using cached response
2023-12-22 08:41:32 [INFO] Executing Step 1: PromptGeneration
2023-12-22 08:41:32 [INFO] Executing Step 2: CodeGenerator
2023-12-22 08:41:32 [INFO] Executing Step 3: CachePopulation
2023-12-22 08:41:32 [INFO] Executing Step 4: CodeExecution
2023-12-22 08:41:32 [INFO] Saving charts to <PATH>
2023-12-22 08:41:32 [INFO] 
Code running:

2023-12-22 08:41:32 [WARNING] Failed to execute code with a correction framework [retry number: 1]
2023-12-22 08:41:32 [ERROR] Failed with error: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/opt/conda/lib/python3.10/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandasai/helpers/code_manager.py", line 212, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned
. Retrying
2023-12-22 08:41:32 [INFO] Using prompt: <dataframe>


The user asked the following question:
Q: Return maximal amount

You generated this python code:
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible value "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }

It fails with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/opt/conda/lib/python3.10/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandasai/helpers/code_manager.py", line 212, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned


Fix the python code above and return the new python code:
2023-12-22 08:41:36 [INFO] HTTP Request: POST<LINK> "HTTP/1.1 200 OK"
2023-12-22 08:41:36 [ERROR] Pipeline failed on step 4: No code found in the response
```

**Comment by danielstankw** [comment]
@gventuri - would you be so kind as to assist ? - I saw it was an issue before and update of pandasAI helped to solve the issue (on your side)

**Comment by cheshic** [comment]
This bug can be reproduced even using the example from the dock with any LLM. For me it is happens most often, when the response needs to display a list of a certain length. 
python 3.11.17
pandasai 1.5.13

<details>
<summary>code</summary>

```
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI


# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# Instantiate a LLM
llm = OpenAI(api_token="####")

df = SmartDataframe(df, config={"llm": llm, "verbose": True})
resp = df.chat('Which are the 5 happiest countries?')
print(resp)
```

</details>

<details>
<summary>log output:</summary>


```
2024-01-03 02:11:00 [INFO] Question: Which are the 5 happiest countries?
2024-01-03 02:11:00 [INFO] Running PandasAI with openai LLM...
2024-01-03 02:11:00 [INFO] Prompt ID: d8355b24-a6a7-4d07-bee8-0502b1aa2ad0
2024-01-03 02:11:00 [INFO] Executing Step 0: CacheLookup
2024-01-03 02:11:00 [INFO] Using cached response
2024-01-03 02:11:00 [INFO] Executing Step 1: PromptGeneration
2024-01-03 02:11:00 [INFO] Executing Step 2: CodeGenerator
2024-01-03 02:11:00 [INFO] Executing Step 3: CachePopulation
2024-01-03 02:11:00 [INFO] Executing Step 4: CodeExecution
2024-01-03 02:11:00 [INFO] Saving charts to D:\GitHub\OmniAI\exports\charts\temp_chart.png
2024-01-03 02:11:00 [INFO] 
Code running:
```
happiest_countries = dfs[0].nlargest(5, 'happiness_index')
        ```
2024-01-03 02:11:00 [WARNING] Failed to execute code with a correction framework [retry number: 1]
2024-01-03 02:11:00 [ERROR] Failed with error: Traceback (most recent call last):
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\pipelines\smart_datalake_chat\code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\helpers\query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\helpers\code_manager.py", line 211, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned
. Retrying
2024-01-03 02:11:00 [INFO] Using prompt: <dataframe>
dfs[0]:10x3
country,gdp,happiness_index
United States,19294482071552,6.94
France,2411255037952,6.66
United Kingdom,2891615567872,7.16
</dataframe>

The user asked the following question:
Q: Which are the 5 happiest countries?

You generated this python code:
# TODO: import the required dependencies
import pandas as pd

# Write code here
happiest_countries = dfs[0].nlargest(5, 'happiness_index')

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "

It fails with the following error:
Traceback (most recent call last):
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\pipelines\smart_datalake_chat\code_execution.py", line 46, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\helpers\query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\OmniAI\venv\Lib\site-packages\pandasai\helpers\code_manager.py", line 211, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned
```
</details>
