### ISSUE TITLE
Skills (eg skill_name() ) can not be run due to "NameError: name 'skill_name' is not defined"

### ISSUE THREAD

**Issue by DavidARivkin** [Sinaptik-AI/pandas-ai#842]
### System Info

Latest version of PandasAI, Ubuntu linux.

### 🐛 Describe the bug

Get the message:  NameError: name 'skill_name' is not defined" for a skill that is defined in the code.  Is there some documentation error or does this just not work?
Eg. 

import pandas as pd
from pandasai import Agent

from pandasai.skills import skill

@skill
def get_dataframe_name(df: pd.DataFrame) -> str:
    """
    Returns the name of the dataframe.
    Args:
        name (str):
    """
    if df is not None and "attrs" in df and "name" in df.attrs:
        return df.attrs['name']
    else:
        return ""

#  This loads the skills given an agent
def loadSkills(agent):
    # 
    agent.add_skills(get_dataframe_name)

The above can not be run on any dataframe due to the error mentioned above.

**Comment by mspronesti** [comment]
Hi @DavidARivkin, please provide a minimal riproducible example.

**Comment by DavidARivkin** [comment]
See above, that makes it happen every time.

**Comment by DavidARivkin** [comment]
Has anyone else taken a look at why Agents dont work at all when it seems like such a major feature of the package?
All you have to do to see this is make the 1 skill above (to get the Name of the dataframe if it exists even) and add it to the agent, then ask the agent for the name of any dataframe in a prompt.  It will error as it cant access the skill after all.  Must be something in the skill decorator that is not working.

**Comment by DavidARivkin** [comment]
I have been tracing into this a bit more.  I see that the text of the code is passed to OpenAI but OpenAI does not return the function back, perhaps it was not asked to, and since the Agent does not pass the Task functions to the Python Execution system, it does not have the code to run.  Perhaps this is the core of the problem.

**Comment by DavidARivkin** [comment]
Here is the transaction with OpenAI I mention above and the traceback on the error:

2024-01-26 11:46:40 The user asked the following question:
2024-01-26 11:46:40 Q: What is the name of the dataframe with the highest cycle count?
2024-01-26 11:46:40 
2024-01-26 11:46:40 You generated this python code:
2024-01-26 11:46:40 # TODO: import the required dependencies
2024-01-26 11:46:40 import pandas as pd
2024-01-26 11:46:40 
2024-01-26 11:46:40 # Write code here
2024-01-26 11:46:40 cycle_counts = [len(df['cycle number'].unique()) for df in dfs]
2024-01-26 11:46:40 max_cycle_count_index = cycle_counts.index(max(cycle_counts))
2024-01-26 11:46:40 df_name = get_dataframe_name(dfs[max_cycle_count_index])
2024-01-26 11:46:40 
2024-01-26 11:46:40 # Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
2024-01-26 11:46:40 result = {
2024-01-26 11:46:40     "type": "string",
2024-01-26 11:46:40     "value": f"The dataframe with the highest cycle count is {df_name}."
2024-01-26 11:46:40 }
2024-01-26 11:46:40 
2024-01-26 11:46:40 result
2024-01-26 11:46:40 
2024-01-26 11:46:40 It fails with the following error:
2024-01-26 11:46:40 Traceback (most recent call last):
2024-01-26 11:46:40   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 46, in execute
2024-01-26 11:46:40     result = pipeline_context.query_exec_tracker.execute_func(
2024-01-26 11:46:40   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
2024-01-26 11:46:40     result = function(*args, **kwargs)
2024-01-26 11:46:40   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/helpers/code_manager.py", line 207, in execute_code
2024-01-26 11:46:40     exec(code_to_run, environment)
2024-01-26 11:46:40   File "<string>", line 3, in <module>
2024-01-26 11:46:40 NameError: name 'get_dataframe_name' is not defined
2024-01-26 11:46:40

**Comment by DavidARivkin** [comment]
Also note that when passed to OpenAI, the function in question is referred to as follows:

def pandasai.skills.get_dataframe_name 

Therefore it make sense to me that then trying to just call 'get_dataframe_name' in this space would be incorrect as it needs to be fully resolved to 'pandasai.skills.get_dataframe_name'

**Comment by mspronesti** [comment]
@DavidARivkin are you sure you are using the latest pandasai? The signature you mentioned was removed in 1.5.12.
Could you please install a newer release?

**Comment by DavidARivkin** [comment]
I dont have the specific version specified in my requirements.txt file it is simply:
pandasai
...

**Comment by DavidARivkin** [comment]
Ok, I did that and while the result is different, it is still not correct.
Instead of an error that the function is not correct, I no longer see the Agents' Task code being sent to OpenAI, and therefore OpenAI tries to come up with a solution, which is incorrect based on the coding system implemented which the Task was meant to use.  Eg.  
INFO:pandasai.helpers.logger:Code generated:
2024-01-29 16:15:07             ```
2024-01-29 16:15:07             # TODO: import the required dependencies
2024-01-29 16:15:07 import pandas as pd
2024-01-29 16:15:07 
2024-01-29 16:15:07 # Write code here
2024-01-29 16:15:07 def get_dataframe_name(df: pd.DataFrame) -> str:
2024-01-29 16:15:07     """
2024-01-29 16:15:07     Returns the name of the dataframe.
2024-01-29 16:15:07     Args:
2024-01-29 16:15:07         df (pd.DataFrame): The dataframe
2024-01-29 16:15:07     Returns:
2024-01-29 16:15:07         The name of the dataframe
2024-01-29 16:15:07     """
2024-01-29 16:15:07     for name, value in globals().items():
2024-01-29 16:15:07         if isinstance(value, pd.DataFrame) and value.equals(df):
2024-01-29 16:15:07             return name
2024-01-29 16:15:07     return ""
2024-01-29 16:15:07 
2024-01-29 16:15:07 dataframe_names = [get_dataframe_name(df) for df in dfs]
2024-01-29 16:15:07 
2024-01-29 16:15:07 # Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
2024-01-29 16:15:07 result = {
2024-01-29 16:15:07     "type": "string",
2024-01-29 16:15:07     "value": dataframe_names
2024-01-29 16:15:07 }
2024-01-29 16:15:07 
2024-01-29 16:15:07 result
2024-01-29 16:15:07             ```
2024-01-29 16:15:07             
2024-01-29 16:15:07 INFO:pandasai.helpers.logger:Executing Step 3: CachePopulation
2024-01-29 16:15:08 INFO:pandasai.helpers.logger:Executing Step 4: CodeExecution
2024-01-29 16:15:08 INFO:pandasai.helpers.logger:Saving charts to /app/collector/exports/charts/temp_chart.png
2024-01-29 16:15:08 INFO:pandasai.helpers.logger:
2024-01-29 16:15:08 Code running:
2024-01-29 16:15:08 ```
2024-01-29 16:15:08 def get_dataframe_name(df: pd.DataFrame) ->str:
2024-01-29 16:15:08     """
2024-01-29 16:15:08     Returns the name of the dataframe.
2024-01-29 16:15:08     Args:
2024-01-29 16:15:08         df (pd.DataFrame): The dataframe
2024-01-29 16:15:08     Returns:
2024-01-29 16:15:08         The name of the dataframe
2024-01-29 16:15:08     """
2024-01-29 16:15:08     for name, value in globals().items():
2024-01-29 16:15:08         if isinstance(value, pd.DataFrame) and value.equals(df):
2024-01-29 16:15:08             return name
2024-01-29 16:15:08     return ''
2024-01-29 16:15:08 
2024-01-29 16:15:08 
2024-01-29 16:15:08 dataframe_names = [get_dataframe_name(df) for df in dfs]
2024-01-29 16:15:08 result = {'type': 'string', 'value': dataframe_names}
2024-01-29 16:15:08 result
2024-01-29 16:15:08         ```
2024-01-29 16:15:08 WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
2024-01-29 16:15:08 ERROR:pandasai.helpers.logger:Failed with error: Traceback (most recent call last):
2024-01-29 16:15:08   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
2024-01-29 16:15:08     result = pipeline_context.query_exec_tracker.execute_func(
2024-01-29 16:15:08   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
2024-01-29 16:15:08     result = function(*args, **kwargs)
2024-01-29 16:15:08   File "/app/collector/v-env/lib/python3.10/site-packages/pandasai/helpers/code_manager.py", line 212, in execute_code
2024-01-29 16:15:08     exec(code_to_run, environment)
2024-01-29 16:15:08   File "<string>", line 15, in <module>
2024-01-29 16:15:08   File "<string>", line 15, in <listcomp>
2024-01-29 16:15:08   File "<string>", line 9, in get_dataframe_name
2024-01-29 16:15:08 NameError: name 'globals' is not defined
2024-01-29 16:15:08 . Retrying
2024-01-29 16:15:08 INFO:pandasai.helpers.logger:Using prompt: <dataframe>
2024-01-29 16:15:08 dfs[0]:1483324x9
2024-01-29 16:15:08 time/s,control/V/mA,Ecell/V,<I>/mA,Q discharge/mA.h,Q charge/mA.h,control/V,control/mA,cycle number
2024-01-29 16:15:08 0.0,1250.0,2.9342027,0.0830847894237694,0.0,0.0006944965955946,0.0,1250.0,1.0
2024-01-29 16:15:08 20.000002086075256,1250.0,3.0238707,1250.0739289333,0.0,6.9455170054796,0.0,1250.0,1.0
2024-01-29 16:15:08 10.000001042964868,1250.0,2.9913824,1250.061913480452,0.0,3.4730890629069013,0.0,1250.0,1.0
2024-01-29 16:15:08 </dataframe>

**Comment by DavidARivkin** [comment]
Also there is a lot of inconsistency in the results.  I did make a small change to the Task function as you will see below, but please explain to me then why does it not even receive the dataframe properly (it gets a NoneType instead) as you can see here:
2024-01-29 19:42:24 DEBUG:httpx._client:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-29 19:42:24 DEBUG:openai._base_client:HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"
2024-01-29 19:42:24 INFO:pandasai.helpers.logger:Saving charts to /app/collector/exports/charts/temp_chart.png
2024-01-29 19:42:24 INFO:pandasai.helpers.logger:
2024-01-29 19:42:24 Code running:
2024-01-29 19:42:24 ```
2024-01-29 19:42:24 def get_dataframe_name(df):
2024-01-29 19:42:24     return df.attrs['name']
2024-01-29 19:42:24 
2024-01-29 19:42:24 
2024-01-29 19:42:24 names = []
2024-01-29 19:42:24 for i, df in enumerate(dfs):
2024-01-29 19:42:24     name = get_dataframe_name(df)
2024-01-29 19:42:24     names.append(name)
2024-01-29 19:42:24 result = {'type': 'string', 'value': f"The names of the dataframes are: {', '.join(names)}."}
2024-01-29 19:42:24 result
2024-01-29 19:42:24         ```
2024-01-29 19:42:24 ERROR:pandasai.helpers.logger:Pipeline failed on step 4: 'NoneType' object has no attribute 'attrs'
2024-01-29 19:42:24 INFO:root:Loaded dataframe names: Unfortunately, I was not able to answer your question, because of the following error:
2024-01-29 19:42:24 
2024-01-29 19:42:24 'NoneType' object has no attribute 'attrs'
2024-01-29 19:42:24 
2024-01-29 19:42:24 INFO:root:Dataframe saved to workspace NCMNCACells as <scripts.dataframe.DataframeHolder object at 0xffff58ab31f0>' using 48 bytes for the dataframe, resulting in a total of 340 bytes
2024-01-29 19:42:24 INFO:     192.168.65.1:28440 - "POST /workspace/new HTTP/1.1" 200 OK

**Comment by DavidARivkin** [comment]
My concern has been repeated in another Issue ticket.
