### ISSUE TITLE
Add Faker into white list or add ability to expand white list.

### ISSUE THREAD

**Issue by PavelAgurov** [Sinaptik-AI/pandas-ai#961]
### 🚀 The feature

Add Faker into white list or add ability to expand white list.

### Motivation, pitch

I've asked question "Generate me 10 new synthetic rows based on provided examples" and got error: 

Generated code includes import of faker which is not in whitelist.

Log:

```
Question: Generate me 10 new synthetic rows based on provided examples
Running PandasAI with openai LLM...
Prompt ID: eb749e24-762f-4807-828c-a52f772666be
<class 'pandasai.helpers.output_types._output_types.DefaultOutputType'> is going to be used.
<class 'pandasai.helpers.viz_library_types._viz_library_types.NoVizLibraryType'> is going to be used.
Executing Step 0: CacheLookup
Executing Step 1: PromptGeneration
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,1,1,"Cumings, Mrs. John Bra...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina...",female,26.0,0,0,STON/O2. 3101282,7.925,,S
1,0,3,"Braund, Mr. Owen Harri...",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>


Update this initial code:
python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }

Q: Generate me 10 new synthetic rows based on provided examples
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

Generate python code and return full updated code:
Executing Step 2: CodeGenerator
Code generated:

            # TODO: import the required dependencies
import pandas as pd
from faker import Faker

# Write code here
fake = Faker()

# Generate 10 new synthetic rows based on provided examples
new_rows = []
for _ in range(10):
    new_row = {
        "PassengerId": fake.random_int(min=4, max=1000),
        "Survived": fake.random_int(min=0, max=1),
        "Pclass": fake.random_int(min=1, max=3),
        "Name": fake.name(),
        "Sex": fake.random_element(elements=["male", "female"]),
        "Age": fake.random_int(min=1, max=80),
        "SibSp": fake.random_int(min=0, max=4),
        "Parch": fake.random_int(min=0, max=2),
        "Ticket": fake.random_int(min=10000, max=99999),
        "Fare": round(fake.random_number(digits=4, fix_len=True), 2),
        "Cabin": fake.random_element(elements=[None, "A1", "B2", "C3"]),
        "Embarked": fake.random_element(elements=["S", "C", "Q"])
    }
    new_rows.append(new_row)

# Create a new DataFrame with the original data plus the 10 new synthetic rows
new_df = pd.concat([dfs[0], pd.DataFrame(new_rows)], ignore_index=True)

# Declare result var
result = {"type": "dataframe", "value": new_df}
            

Executing Step 3: CachePopulation
Executing Step 4: CodeExecution
Failed to execute code with a correction framework [retry number: 1]
Failed with error: Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 186, in execute_code
    code_to_run = self._clean_code(code, context)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 375, in _clean_code
    self._check_imports(node)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 456, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of faker which is not in whitelist.
. Retrying
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,1,1,"Cumings, Mrs. John Bra...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina...",female,26.0,0,0,STON/O2. 3101282,7.925,,S
1,0,3,"Braund, Mr. Owen Harri...",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>

The user asked the following question:
Q: Generate me 10 new synthetic rows based on provided examples

You generated this python code:
# TODO: import the required dependencies
import pandas as pd
from faker import Faker

# Write code here
fake = Faker()

# Generate 10 new synthetic rows based on provided examples
new_rows = []
for _ in range(10):
    new_row = {
        "PassengerId": fake.random_int(min=4, max=1000),
        "Survived": fake.random_int(min=0, max=1),
        "Pclass": fake.random_int(min=1, max=3),
        "Name": fake.name(),
        "Sex": fake.random_element(elements=["male", "female"]),
        "Age": fake.random_int(min=1, max=80),
        "SibSp": fake.random_int(min=0, max=4),
        "Parch": fake.random_int(min=0, max=2),
        "Ticket": fake.random_int(min=10000, max=99999),
        "Fare": round(fake.random_number(digits=4, fix_len=True), 2),
        "Cabin": fake.random_element(elements=[None, "A1", "B2", "C3"]),
        "Embarked": fake.random_element(elements=["S", "C", "Q"])
    }
    new_rows.append(new_row)

# Create a new DataFrame with the original data plus the 10 new synthetic rows
new_df = pd.concat([dfs[0], pd.DataFrame(new_rows)], ignore_index=True)

# Declare result var
result = {"type": "dataframe", "value": new_df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 186, in execute_code
    code_to_run = self._clean_code(code, context)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 375, in _clean_code
    self._check_imports(node)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 456, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of faker which is not in whitelist.


Fix the python code above and return the new python code:
Failed to execute code with a correction framework [retry number: 2]
Failed with error: Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 186, in execute_code
    code_to_run = self._clean_code(code, context)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 375, in _clean_code
    self._check_imports(node)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 456, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of faker which is not in whitelist.
. Retrying
Using prompt: <dataframe>
dfs[0]:891x12
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,1,1,"Cumings, Mrs. John Bra...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina...",female,26.0,0,0,STON/O2. 3101282,7.925,,S
1,0,3,"Braund, Mr. Owen Harri...",male,22.0,1,0,A/5 21171,7.25,,S
</dataframe>

The user asked the following question:
Q: Generate me 10 new synthetic rows based on provided examples

You generated this python code:
# TODO: import the required dependencies
import pandas as pd
from faker import Faker

# Write code here
fake = Faker()

# Generate 10 new synthetic rows based on provided examples
new_rows = []
for _ in range(10):
    new_row = {
        "PassengerId": fake.random_int(min=4, max=1000),
        "Survived": fake.random_int(min=0, max=1),
        "Pclass": fake.random_int(min=1, max=3),
        "Name": fake.name(),
        "Sex": fake.random_element(elements=["male", "female"]),
        "Age": fake.random_int(min=1, max=80),
        "SibSp": fake.random_int(min=0, max=4),
        "Parch": fake.random_int(min=0, max=2),
        "Ticket": fake.random_int(min=10000, max=99999),
        "Fare": round(fake.random_number(digits=4, fix_len=True), 2),
        "Cabin": fake.random_element(elements=[None, "A1", "B2", "C3"]),
        "Embarked": fake.random_element(elements=["S", "C", "Q"])
    }
    new_rows.append(new_row)

# Create a new DataFrame with the original data plus the 10 new synthetic rows
new_df = pd.concat([dfs[0], pd.DataFrame(new_rows)], ignore_index=True)

# Declare result var
result = {"type": "dataframe", "value": new_df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/pipelines/smart_datalake_chat/code_execution.py", line 53, in execute
    result = pipeline_context.query_exec_tracker.execute_func(
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/query_exec_tracker.py", line 128, in execute_func
    result = function(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 186, in execute_code
    code_to_run = self._clean_code(code, context)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 375, in _clean_code
    self._check_imports(node)
  File "/home/adminuser/venv/lib/python3.9/site-packages/pandasai/helpers/code_manager.py", line 456, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of faker which is not in whitelist.


Fix the python code above and return the new python code:
Pipeline failed on step 4: Generated code includes import of faker which is not in whitelist.
```

**Comment by PavelAgurov** [comment]
Sorry, it seems I found custom_whitelisted_dependencies, will try and report.

**Comment by PavelAgurov** [comment]
Version 2.0.2 doesn't trying to use Faker, it uses random.

With question "Generate me 10 synthetic rows based on provided examples using Faker library" it works fine:

    smart_df = SmartDatalake(st.session_state.data, config={
                      ...........
                    "custom_whitelisted_dependencies" : ["faker"]
