### ISSUE TITLE
Doesn't work in AzureOpenAI

### ISSUE THREAD

**Issue by Rainismer** [Sinaptik-AI/pandas-ai#976]
### System Info

OS version: win10
Python version: python 3.11
Code：
from pandasai import SmartDataframe
from langchain_openai import AzureChatOpenAI
import pandas as pd
import os

os.environ["PANDASAI_API_KEY"] = "......BTn6"
**llm = AzureChatOpenAI(
openai_api_key=config.azure_openai_api_key,
openai_api_version=config.azure_openai_api_version,
azure_endpoint=config.azure_openai_endpoint,
azure_deployment=config.model_name
)**
sales_by_country = pd.DataFrame({
"country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
"sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})
df = SmartDataframe(sales_by_country, config={"llm": llm})
response = df.chat('Which are the top 5 countries by sales?')
print(response)

### 🐛 Describe the bug

Traceback (most recent call last):
  File "D:\Projects\dataCopilot-web\333.py", line 165, in <module>
    agent = Agent(
            ^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\agent\base.py", line 74, in __init__
    config = self.get_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\agent\base.py", line 147, in get_config
    config = Config(**config)
             ^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\main.py", line 1074, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\fields.py", line 895, in validate
    v, errors = self._apply_validators(v, values, loc, cls, self.post_validators)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\fields.py", line 1154, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pydantic\v1\class_validators.py", line 304, in <lambda>
    return lambda cls, v, values, field, config: validator(cls, v)
                                                 ^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\schemas\df_config.py", line 41, in validate_llm
    raise LLMNotFoundError("LLM is required")
pandasai.exceptions.LLMNotFoundError: LLM is required

**Comment by mspronesti** [comment]
Hi @Rainismer, I believe 2.0 would not work with any LLM from langchain. I opened #977 to patch this. Could you please try it out and let me know if that works for you?
