### ISSUE TITLE
File exists error when creating a `SmartDataframe` object

### ISSUE THREAD

**Issue by araghuvanshi-systango** [Sinaptik-AI/pandas-ai#993]
### System Info

OS version: Ubuntu 20.04.6 LTS
Python version: 3.11.8
The current version of `pandasai` being used: 2.0.3

### 🐛 Describe the bug

Here is the code (simple flask API) that I'm using right now:

```python
# Route to get all books
@app.route('/run', methods=['POST'])
def run_pandasai():
    data = request.get_json()
    engine = create_engine(SQLALCHEMY_BASE_DATABASE_URI)
    df = None
    with engine.connect() as conn:
        df = pd.read_sql(text(f'SELECT * FROM some_table;'), conn)
    llm = OpenAI(api_token='<my_api_key>')
    df = SmartDataframe(df, config={"llm": llm})
    response = df.chat(some prompt?')
    return jsonify({'response': response})
```

I get the following error while running this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 20, in run_pandasai
    df = SmartDataframe(df, config={"llm": llm})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandasai/smart_dataframe/__init__.py", line 64, in __init__
    self._agent = Agent([df], config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandasai/agent/base.py", line 75, in __init__
    self.context = PipelineContext(
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandasai/pipelines/pipeline_context.py", line 35, in __init__
    self.cache = cache if cache is not None else Cache()
                                                 ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandasai/helpers/cache.py", line 29, in __init__
    os.makedirs(cache_dir, mode=DEFAULT_FILE_PERMISSIONS, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/app/cache'
```

I can understand that this issue is because it is trying to create the dir that already exists, and even though the exist_ok is `True` the `DEFAULT_FILE_PERMISSIONS` is such that it can't create in and it fails, is this a bug?

**Comment by araghuvanshi-systango** [comment]
Just an update, this only happens inside a docker container to fix this I did the following:

```
SmartDataframe(df, config={"llm": llm, "enable_cache": False, "verbose": True})
```

**Comment by gventuri** [comment]
@araghuvanshi-systango seems to be an issue with the cache, that cannot write on the folder because it doesn't exist.
There are 2 options here:
- disable the cache (as in the example above)
- configuring `app/cache` folder in your docker configuration
